### Ruby's raise vs throw
* raise, fail, rescue, and ensure handle errors, also known as *exceptions*
* throw and catch are control flow; they emulate a "go to": Ruby's throw/catch lets you break execution and climb up the stack looking for a catch (like raise/rescue does), but isn't really meant for error conditions. It should be used rarely, and is there just for when the "walk up the stack until you find a corresponding catch" behaviour makes sense for an algorithm you're writing but it wouldn't make sense to think of the throw as corresponding to an error condition.
(you can use it if for example you wanna break 16 nested loops or the snippet you wanna execute is far far away, maybe in another method)

Throw example:
```ruby
def inicio
  $l = 0
  catch(:stop) do
    while true
      metodo_a
    end
  end
  puts "Terminamos!"
end

def ll(metodo)
  $l += 1
  puts "#{' ' * $l}#{metodo}"
end

def metodo_a
  ll __method__
  if rand(0..1) == 0
    metodo_b
  else
    metodo_c
  end
end

def metodo_b
  ll __method__
  metodo_d
end

def metodo_c
  ll __method__
  metodo_i
end

def metodo_d
  ll __method__
  case rand(0..4)
    when 0
      throw :stop
    when 1
      metodo_e
    when 2
      metodo_f
    when 3
      metodo_g
    when 4
      metodo_h
  end
end

def metodo_e
  ll __method__
  metodo_a
end

def metodo_f
  ll __method__
  metodo_i
end

def metodo_g
  ll __method__
  metodo_d
end

def metodo_h
  ll __method__
  metodo_g
end

def metodo_i
  ll __method__
  metodo_d
end

inicio
```